project:
  type: book
  output-dir: docs

book:
  title: "Diseño Experimental y análisis de Datos"
  #author: "Juan A. Ugalde"
  #date: "2022"
  chapters:
    - index.qmd
    - part: A_introR.qmd
      chapters: 
      - A1_intro_config.qmd
      - A2_intro_env.qmd
  page-navigation: true
  site-url: https://microbialds.github.io/ExpDesign/
  repo-url: https://github.com/microbialds/ExpDesign.
  repo-branch: master
  

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
  pdf:
    documentclass: scrbook

editor: visual

